ops:
  fasta_gz:
    config:
      input_folder: /run/media/herminio/VirginieG/rna-sequence/data/inputs
      input_pattern: '*.gz'
  fasta_md5:
    config:
      input_folder: /run/media/herminio/VirginieG/rna-sequence/data/inputs
      input_pattern: MD5.txt
  fastq_concat:
    config:
      input_folder: /run/media/herminio/VirginieG/rna-sequence/data/inputs
      output_folder: data/outputs/merged_fastq
